//
// structured configuration; see #13752
//

#pragma once

// BLTOUCH: work around issue #13368
#undef DEACTIVATE_SERVOS_AFTER_MOVE

#define EMERGENCY_PARSER

#define BINARY_FILE_TRANSFER

#define DIGIPOT_I2C
#define DIGIPOT_I2C_ADDRESS_A 0x2C
#define DIGIPOT_I2C_ADDRESS_B 0x2D

#undef  DIGIPOT_I2C_NUM_CHANNELS
#define DIGIPOT_I2C_NUM_CHANNELS 5

#undef  DIGIPOT_I2C_MOTOR_CURRENTS
#define DIGIPOT_I2C_MOTOR_CURRENTS { 1.4, 1.4, 1.4, 1.2, 1.2 }

#define LIN_ADVANCE
#define LIN_ADVANCE_K 0.22

#define CASE_LIGHT_ENABLE
#define CASE_LIGHT_DEFAULT_ON true
#define CASE_LIGHT_DEFAULT_BRIGHTNESS 255

#undef  X_HOME_BUMP_MM
#undef  Y_HOME_BUMP_MM
#undef  Z_HOME_BUMP_MM
#undef  HOMING_BUMP_DIVISOR
#define X_HOME_BUMP_MM 4
#define Y_HOME_BUMP_MM 4
#define Z_HOME_BUMP_MM 2
#define HOMING_BUMP_DIVISOR { 5, 5, 10 }

// note: verify jumpers
#undef  MICROSTEP_MODES
#define MICROSTEP_MODES { 32, 32, 32, 32, 32 }

#define MINIMUM_STEPPER_DIR_DELAY 1000

#define MINIMUM_STEPPER_PULSE 4

#define MAXIMUM_STEPPER_RATE 250000

#define ADAPTIVE_STEP_SMOOTHING

#undef  CHAMBER_MINTEMP
#undef  CHAMBER_MAXTEMP
#define CHAMBER_MINTEMP            10
#define CHAMBER_MAXTEMP            90

#undef  THERMAL_PROTECTION_CHAMBER_PERIOD
#undef  THERMAL_PROTECTION_CHAMBER_HYSTERESIS
#define THERMAL_PROTECTION_CHAMBER_PERIOD     60 // Seconds
#define THERMAL_PROTECTION_CHAMBER_HYSTERESIS 1  // Celsius
